version: 1.0.0-{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu1804

build_script:
- sh: >-
    cd backend/
    
    go version

    go build ./main.go
test_script:
- sh: go test ./...