version: '3'

services:
    influx:
      ports:
        - 8086:8086

    meteo-agent:
      image: vladikan/meteo-agent:latest
      build: .
      environment:
        - MA_INFLUX_TOKEN=development-token