version: '3'

services:
    influx:
      image: influxdb:1.8
      container_name: "influx"
      hostname: "influx"
      restart: always

      volumes:
        - influxdata:/var/lib/influxdb

      environment:
        - INFLUXDB_HTTP_AUTH_ENABLED=true
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=YWRtaW4=

    meteo_agent:
      image: vladikan/meteo-agent:latest
      container_name: "meteo-agent"
      hostname: "meteo-agent"
      restart: always
      
      depends_on:
        - influx
  
      logging:
        driver: json-file
        options:
            max-size: "5m"
            max-file: "5"
  
      environment:
        - MA_DEBUG=false
        - MA_ADDRESS
        - MA_SSL
        - MA_WHITELIST
        - MA_INFLUXHOST
        - MA_INFLUXUSER
        - MA_INFLUXPASSWORD
        
volumes:
    influxdata: